# Nome do executável
TARGET = jogopif

# Compilador e flags
CC = gcc
CFLAGS = -Wall -Wextra -std=c11

# Arquivos fonte
SRC = main.c screen.c keyboard.c timer.c
OBJ = $(SRC:.c=.o)

# Regra padrão
all: $(TARGET)

# Regras de compilação
$(TARGET): $(OBJ)
  $(CC) $(CFLAGS) -o $@ $^

# Regra para arquivos objeto
%.o: %.c
  $(CC) $(CFLAGS) -c $< -o $@

# Limpeza
clean:
  rm -f $(OBJ) $(TARGET)

make
